python: '3.6'

language: python

sudo: false

env:
    - TOX_ENV=py36-flake8

    - TOX_ENV=py36-django2.0.5-drf3.6

matrix:
  fast_finish: true

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
