language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

matrix:
  fast_finish: true

install: pip install tox-travis

script: tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
